# Generated by Django 5.2.7 on 2025-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, unique=True, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('talla', models.FloatField(verbose_name='Talla')),
                ('stock', models.PositiveSmallIntegerField(max_length=2, verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='zapatos/', verbose_name='Imagen')),
            ],
        ),
    ]
