# Generated by Django 6.0 on 2025-12-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='zapatos/')),
                ('stock', models.IntegerField(default=0)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapatos', to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='VariacionTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField(max_length=2)),
                ('stock', models.IntegerField()),
                ('zapato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallas', to='inventario.zapato')),
            ],
        ),
    ]
